---
Name: admintoolbar
---

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - WeDevelop\AdminToolbar\Extensions\SiteTreeExtension

SilverStripe\Security\Member:
  extensions:
    - WeDevelop\AdminToolbar\Extensions\MemberExtension

WeDevelop\AdminToolbar\AdminToolbar:
  disabled_menus:
  disabled_menu_items:
  disabled_buttons:
  disabled_toggles:

---
Only:
  environment: 'live'
---
WeDevelop\AdminToolbar\AdminToolbar:
  disabled_menus:
  disabled_menu_items:
  disabled_buttons:
    - 'Queries'
  disabled_toggles:
    - 'Queries'
